DROP TABLE IF EXISTS Users;

CREATE TABLE Users(
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(45) NOT NULL,
    surname VARCHAR(45) NOT NULL,
    sex VARCHAR(45) NOT NULL,
    birth DATE NOT NULL,
    phone INTEGER NOT NULL,
    email VARCHAR(45) NOT NULL,
    work_position VARCHAR(45) NOT NULL,
    cp INTEGER NOT NULL,

    PRIMARY KEY (id)
);

INSERT INTO Users (name, surname, sex, birth, phone, email, work_position, cp)
VALUES ('Idoia', 'Redorta', 'Female', '1994-12-21', 666666666, 'iarz@gft.com', 'Graduate', 25001);

INSERT INTO Users (name, surname, sex, birth, phone, email, work_position, cp)
VALUES ('Antonio', 'García', 'Male', '1992-01-12', 600112233, 'antonio.garcia@example.com', 'Manager', 28003);

INSERT INTO Users (name, surname, sex, birth, phone, email, work_position, cp)
VALUES ('Idoia', 'Martínez', 'Female', '1988-06-07', 677889900, 'idoia.martinez@example.com', 'Developer', 28004);

INSERT INTO Users (name, surname, sex, birth, phone, email, work_position, cp)
VALUES ('Sofía', 'López', 'Female', '1997-11-03', 677889900, 'sofia.lopez@example.com', 'Designer', 28005);